name: "demo-redis-biquery"
services:
  redis:
    container_name: demo-redis-bigquery-redis
    image: "redis:8.0-M02"
    ports:
      - 6379:6379
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - redis-data:/data

  app:
    container_name: demo-redis-bigquery-app
    build:
      context: ./
    command: bun dev
    ports:
      - "${PORT-8080}:${PORT-8080}"
    environment:
      PORT: ${PORT-8080}
    env_file:
      - ./.env
      - ./.env.docker
    restart: always
    depends_on:
      - redis

volumes:
  redis-data:
